//! Deterministic render of DesiredState into sing-box JSON and nft rules.
//! Pure functions: same config in, byte-identical artifacts out (golden-tested).
//! sing-box target: 1.13.x action-based route/DNS schema, pinned deliberately.

use ipnet::IpNet;
use serde_json::{json, Map, Value};

use crate::config::{DnsMode, GatewayConfig, Policy, Route, RoutingMode};

/// ponytail: spike 0 does not resolve subscriptions; the vpn outbound is a
/// structurally valid placeholder. v1 replaces it via resolve-subscription.
pub const PLACEHOLDER_OUTBOUND: &str = "vpn-out";

pub fn render_sing_box(cfg: &GatewayConfig) -> String {
    let mut rules: Vec<Value> = vec![
        json!({ "action": "sniff", "timeout": "300ms" }),
        json!({ "protocol": "dns", "action": "hijack-dns" }),
        json!({ "ip_is_private": true, "outbound": "direct" }),
    ];
    for src in &cfg.management.sources {
        rules.push(json!({ "source_ip_cidr": [src.to_string()], "outbound": "direct" }));
    }
    for p in &cfg.policies {
        let mut r = Map::new();
        r.insert("source_ip_cidr".to_string(), json!([p.source.to_string()]));
        if let Some(proto) = p.protocol {
            r.insert("network".to_string(), json!(proto.as_str()));
        }
        if let Some(port) = p.port {
            r.insert("port".to_string(), json!([port]));
        }
        match p.route {
            Route::Vpn => r.insert("outbound".to_string(), json!(PLACEHOLDER_OUTBOUND)),
            Route::Direct => r.insert("outbound".to_string(), json!("direct")),
            Route::Block => r.insert("action".to_string(), json!("reject")),
        };
        rules.push(Value::Object(r));
    }

    let mut dns_servers = vec![json!({ "type": "https", "tag": "local-dns", "server": "1.1.1.1" })];
    if cfg.dns.mode == DnsMode::Tunneled {
        dns_servers.insert(
            0,
            json!({ "type": "https", "tag": "vpn-dns", "server": "1.1.1.1", "detour": PLACEHOLDER_OUTBOUND }),
        );
    }
    let dns_final = match cfg.dns.mode {
        DnsMode::Tunneled => "vpn-dns",
        DnsMode::Direct => "local-dns",
    };

    let mut inbound = json!({
        "type": "tun",
        "tag": "tun-in",
        "interface_name": "vpnr-tun",
        "address": ["172.19.0.1/30"],
        "mtu": cfg.tun.mtu,
        "auto_route": true,
        "strict_route": false,
        "stack": "system"
    });
    if !cfg.management.sources.is_empty() {
        // Host routing to admin hosts bypasses the tun entirely: SSH return
        // traffic stays alive even when sing-box is down or misrouting.
        inbound["route_exclude_address"] = json!(cfg
            .management
            .sources
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>());
    }

    let final_outbound = match cfg.routing.mode {
        RoutingMode::Full => PLACEHOLDER_OUTBOUND,
        RoutingMode::Split => "direct",
    };

    let config = json!({
        "log": { "level": "info" },
        "dns": {
            "servers": dns_servers,
            "final": dns_final,
            "strategy": "ipv4_only"
        },
        "inbounds": [inbound],
        "outbounds": [
            {
                "type": "vless",
                "tag": PLACEHOLDER_OUTBOUND,
                "server": "placeholder.invalid",
                "server_port": 443,
                "uuid": "00000000-0000-0000-0000-000000000000",
                "tls": { "enabled": true, "server_name": "placeholder.invalid" }
            },
            { "type": "direct", "tag": "direct" }
        ],
        "route": {
            "rules": rules,
            "final": final_outbound,
            "auto_detect_interface": true,
            "default_domain_resolver": "local-dns"
        }
    });

    let mut s = serde_json::to_string_pretty(&config).expect("static JSON shape");
    s.push('\n');
    s
}

/// Renders our nftables table. Invariants: exactly one owned table
/// (`inet vpnrouter`), never a global flush; the killswitch is a *static*
/// rule that only bites when routing falls back from tun to WAN.
pub fn render_nft(cfg: &GatewayConfig) -> String {
    let wan = &cfg.interfaces.wan;
    let lan = &cfg.interfaces.lan;
    let ks = cfg.killswitch.enabled;
    let mut out = String::new();
    out.push_str("# Generated by vpnrouter-gateway (spike 0). Do not edit.\n");
    out.push_str("# Owns exactly one table: inet vpnrouter. Never flushes the global ruleset.\n");
    out.push_str("# declare + delete + redefine = atomic replace of our table only.\n");
    out.push_str("table inet vpnrouter\n");
    out.push_str("delete table inet vpnrouter\n");
    out.push_str("table inet vpnrouter {\n");
    out.push_str("    chain forward {\n");
    out.push_str("        type filter hook forward priority 0; policy accept;\n");
    for src in &cfg.management.sources {
        out.push_str(&format!(
            "        iifname \"{lan}\" {} saddr {src} accept comment \"vpnr:management\"\n",
            addr_family(src)
        ));
    }
    // Mirror first-match policy semantics in the kernel: direct accepts
    // toward WAN, vpn drops toward WAN (killswitch), block drops everywhere.
    for p in &cfg.policies {
        let fam = addr_family(&p.source);
        let l4 = l4_match(p);
        match p.route {
            Route::Block => out.push_str(&format!(
                "        iifname \"{lan}\" {fam} saddr {} {l4}drop comment \"vpnr:policy:{}\"\n",
                p.source, p.name
            )),
            Route::Direct => out.push_str(&format!(
                "        iifname \"{lan}\" oifname \"{wan}\" {fam} saddr {} {l4}accept comment \"vpnr:policy:{}\"\n",
                p.source, p.name
            )),
            Route::Vpn => {
                if ks {
                    out.push_str(&format!(
                        "        iifname \"{lan}\" oifname \"{wan}\" {fam} saddr {} {l4}drop comment \"vpnr:killswitch:{}\"\n",
                        p.source, p.name
                    ));
                }
            }
        }
    }
    if ks && cfg.routing.mode == RoutingMode::Full {
        // mode=full routes unmatched sources through vpn too — killswitch
        // must cover the whole LAN, not just explicit vpn policies.
        out.push_str(&format!(
            "        iifname \"{lan}\" oifname \"{wan}\" {} saddr {} drop comment \"vpnr:killswitch-final\"\n",
            addr_family(&cfg.interfaces.lan_cidr),
            cfg.interfaces.lan_cidr
        ));
    }
    if ks {
        // sing-box config is ipv4_only; forwarded IPv6 would silently bypass it.
        out.push_str(&format!(
            "        iifname \"{lan}\" oifname \"{wan}\" meta nfproto ipv6 drop comment \"vpnr:killswitch-v6\"\n"
        ));
    }
    out.push_str("    }\n");
    out.push('\n');
    out.push_str("    chain postrouting {\n");
    out.push_str("        type nat hook postrouting priority srcnat; policy accept;\n");
    // direct-routed and management traffic is forwarded in-kernel and needs
    // NAT; vpn traffic is NATed by sing-box itself.
    out.push_str(&format!(
        "        oifname \"{wan}\" masquerade comment \"vpnr:nat\"\n"
    ));
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn addr_family(net: &IpNet) -> &'static str {
    match net {
        IpNet::V4(_) => "ip",
        IpNet::V6(_) => "ip6",
    }
}

fn l4_match(p: &Policy) -> String {
    match (p.protocol, p.port) {
        (Some(proto), Some(port)) => format!("{} dport {} ", proto.as_str(), port),
        (Some(proto), None) => format!("meta l4proto {} ", proto.as_str()),
        _ => String::new(),
    }
}
